export const GET_COACHES_LIST = 'GET_COACHES_LIST';
export const GET_COACHES_LIST_SUCCESS = 'GET_COACHES_LIST_SUCCESS';

export const GET_DETAILED_COACH = 'GET_DETAILED_COACH';
export const GET_DETAILED_COACH_SUCCESS = 'GET_DETAILED_COACH_SUCCESS';