export const GET_WORKOUTS_LIST = 'GET_WORKOUTS_LIST';
export const GET_WORKOUTS_LIST_SUCCESS = 'GET_WORKOUTS_LIST_SUCCESS';

export const GET_WORKOUT_BY_ID = 'GET_WORKOUT_BY_ID';
export const GET_WORKOUT_BY_ID_SUCCESS = 'GET_WORKOUT_BY_ID_SUCCESS';

export const GET_WORKOUT_TYPES = 'GET_WORKOUT_TYPES';
export const GET_WORKOUT_TYPES_SUCCESS = 'GET_WORKOUT_TYPES_SUCCESS';

export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const GET_FILTER_DATA_SUCCESS = 'GET_FILTER_DATA_SUCCESS';

export const EDIT_WORKOUT = 'EDIT_WORKOUT';
export const EDIT_WORKOUT_SUCCESS = 'EDIT_WORKOUT_SUCCESS';