name: REACT CI CD 

on:
  push:
    branches: [ "master" ]
    
jobs:
  reactBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    env: 
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Create .env file
        run: echo "$ENV" > .env
      - name: Create key file
        run: echo "${{ secrets.ID_RSA }}" > .id_rsa
      - run: chmod og= .id_rsa
      - run: apk update && apk add openssh-client
      - name: React build
        run: npm run build --if-present
      - name: Remove old server build folder
        run: ssh -i .id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_API }} "rm -rf /root/build"
      - name: Ubdate servder build folder
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /root/build
          host: ${{ secrets.SERVER_API }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.ID_RSA }}
      - name: Docker compose resstart 
        run: ssh -i .id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_API }} "docker-compose kill -s SIGHUP webserver"
